sudo: required
services:
  - docker
before_install:
  - docker build -t alexwong/docker-react -f Dockerfile.dev .

script:
  - docker run alexwong/docker-react npm run test -- --coverage   
 
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-261783892721"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encypted <secret-access-key>="